apiVersion: ttl.example.com/v1alpha1
kind: TTLResource
metadata:
  labels:
    app.kubernetes.io/name: ttl-operator
    app.kubernetes.io/managed-by: kustomize
  name: ttlresource-test
spec:
  ttlSeconds: 30